volumes:
  php-fpm-socket:
services:
  loadbalancer:
    build: ./loadbalancer
    image: cont/loadbalancer
    container_name: "loadbalancer"
    restart: always
    ports: ["80:80"]
    depends_on:
      - nginx
      - nginx2

  nginx:
    build: ./nginx
    image: cont/web
    container_name: "nginx"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./html:/var/www/html
    restart: always
    depends_on: ["php"]

  php:
    build: ./php
    image: cont/app
    container_name: "php"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./html:/var/www/html

  nginx2:
    build: ./nginx2
    image: cont/web2
    container_name: "nginx2"
    volumes:
      - ./html2:/var/www/html
    restart: always
